import { useEffect, useRef, useState } from 'react'
import { apiRequest, OCR_API_URL } from '../api.js'

const allowedTypes = ['image/jpeg', 'image/png', 'image/webp']
const formatDate = (value) => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T00:00:00`))

function ProductScan() {
  const videoRef = useRef(null), fileRef = useRef(null), streamRef = useRef(null)
  const [step, setStep] = useState('product'), [mode, setMode] = useState(null), [image, setImage] = useState(null), [product, setProduct] = useState(null), [expiry, setExpiry] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  const stopCamera = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null }
  useEffect(() => () => { stopCamera(); if (image?.url) URL.revokeObjectURL(image.url) }, [image])
  function resetImage() { stopCamera(); if (image?.url) URL.revokeObjectURL(image.url); setImage(null); setMode(null); setError('') }
  async function openCamera() { resetImage(); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); streamRef.current = stream; setMode('camera'); setTimeout(() => { if (videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play() } }, 0) } catch { setError('Camera access is unavailable. Please use Upload Image instead.') } }
  function capture() { const video = videoRef.current; if (!video?.videoWidth) return setError('The camera is not ready yet. Please try again.'); const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0); canvas.toBlob((blob) => { if (blob) { stopCamera(); setImage({ file: new File([blob], `${step}-scan.jpg`, { type: 'image/jpeg' }), url: URL.createObjectURL(blob) }); setMode('preview') } }, 'image/jpeg', .92) }
  function selectFile(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (!allowedTypes.includes(file.type)) return setError('Please select a JPG, JPEG, PNG, or WEBP image.'); resetImage(); setImage({ file, url: URL.createObjectURL(file) }); setMode('preview') }
  async function callOcr(path, file) { const body = new FormData(); body.append('image', file); let response; try { response = await fetch(`${OCR_API_URL}${path}`, { method: 'POST', body }) } catch { throw new Error('The image-scanning service is not running. Start the Flask service on port 5000, then try again.') } const data = await response.json().catch(() => ({})); if (!response.ok || !data.success) throw new Error(data.message || 'The image could not be processed.'); return data }
  async function useImage() { if (!image?.file) return; setLoading(true); setError(''); setMessage(''); try { if (step === 'product') { const scan = await callOcr('/api/scan-product', image.file); const match = await apiRequest('/api/scanner/product-match', { method: 'POST', body: JSON.stringify({ text: scan.detected_text }) }); setProduct({ ...match.product, needsReview: match.needsReview || false, quantity: scan.quantity || match.product.quantity || '' }); resetImage(); setStep('expiry') } else { const scan = await callOcr('/api/scan-expiry', image.file); setExpiry(scan); resetImage(); setStep('confirm') } } catch (scanError) { const fallback = step === 'product' ? 'Unable to identify the product. Please make sure the front of the package is clearly visible and try again.' : 'Expiry date could not be detected. Please take a clear close-up image of the expiry information and try again.'; setError(scanError?.message || fallback) } finally { setLoading(false) } }
  async function addToPantry() { if (!product || !expiry?.expiry_date) return; setLoading(true); setError(''); try { await apiRequest('/api/expiry-products', { method: 'POST', body: JSON.stringify({ receiptFileName: 'Product scan', source: 'product-scan', products: [{ name: product.name, brand: product.brand, category: product.category, quantity: product.quantity, image: product.image, expiryDate: expiry.expiry_date, manufacturingDate: expiry.manufacturing_date || null, source: 'product-scan' }] }) }); setMessage('Product added to your Digital Pantry. Expiry reminders are now active.') } catch (saveError) { setError(saveError.message === 'Not authenticated.' ? 'Please log in to add this product to your pantry.' : saveError.message) } finally { setLoading(false) } }
  function startOver() { resetImage(); setProduct(null); setExpiry(null); setStep('product'); setError(''); setMessage('') }
  const title = step === 'product' ? 'Step 1: Scan Product' : step === 'expiry' ? 'Step 2: Scan Expiry' : 'Confirm product details'
  const hint = step === 'product' ? 'Capture the front of the grocery package so we can identify it.' : 'Capture a close-up of the printed expiry or best-before information.'
  return <div className="product-scan"><span className="modal-icon">📷</span><h2>{title}</h2>{step !== 'confirm' && <p>{hint}</p>}{step !== 'confirm' && <><input ref={fileRef} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={selectFile} />{mode === 'camera' && <div className="product-camera"><video ref={videoRef} muted playsInline /><button type="button" onClick={capture}>Capture image</button></div>}{mode === 'preview' && image && <div className="product-image-preview"><img src={image.url} alt={`${step} preview`} /><div><button type="button" onClick={resetImage}>Retake</button><button type="button" className="product-primary" onClick={useImage} disabled={loading}>{loading ? 'Processing…' : 'Use Image'}</button></div></div>}{!mode && <div className="product-actions"><button type="button" className="product-primary" onClick={openCamera}>📷 Scan</button><button type="button" onClick={() => fileRef.current?.click()}>↑ Upload Image</button></div>}</>}{step === 'expiry' && product && <div className="product-found"><small>{product.needsReview ? 'PRODUCT NAME NEEDS REVIEW' : 'PRODUCT FOUND ✓'}</small>{product.needsReview ? <label>Review product name<input value={product.name} onChange={(event) => setProduct({ ...product, name: event.target.value })} /></label> : <strong>{product.name}</strong>}<span>{product.category}{product.quantity ? ` · ${product.quantity}` : ''}</span></div>}{step === 'confirm' && product && expiry && <div className="product-confirm"><small>EXPIRY DETECTED ✓</small>{product.needsReview ? <label>Confirm product name<input value={product.name} onChange={(event) => setProduct({ ...product, name: event.target.value })} /></label> : <strong>{product.name}</strong>}<span>{product.category}</span><h3>{formatDate(expiry.expiry_date)}</h3><button type="button" className="product-primary" onClick={addToPantry} disabled={loading || !product.name.trim()}>{loading ? 'Adding…' : '✓ Confirm & Add to Digital Pantry'}</button><button type="button" onClick={() => { setExpiry(null); setStep('expiry') }}>↻ Scan Again</button></div>}{error && <div className="product-scan-error" role="alert">{error}<div><button type="button" onClick={resetImage}>Try Again</button><button type="button" onClick={() => fileRef.current?.click()}>Upload Another Image</button></div></div>}{message && <p className="product-scan-message" role="status">✓ {message}</p>}{message && <button type="button" onClick={startOver}>Scan another product</button>}</div>
}
export default ProductScan
